ProyectoWeb/ProyectoWeb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('proyectoWebApp.urls')), # Si el primer arg es una ruta, pasa por ahi primero
    path('project_app/', include('proyectoWebApp.urls')), # Si el primer arg queda vacio, pasa derecho

    path('servicios', include('servicios.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),

    path('carrito/', include('carrito.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('pedidos/', include('pedidos.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoWeb/blog/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('', views.blog, name='blog'),
    path('categoria/<int:categoria_id>', views.categoria, name='categoria')
]

ProyectoWeb/carrito/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "carrito"

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_producto, name='agregar'),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar'),
    path('restar/<int:producto_id>/', views.restar_producto, name='restar'),
    path('vaciar/', views.vaciar, name='vaciar'),
]

ProyectoWeb/tienda/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('', views.tienda, name='tienda'),
]

ProyectoWeb/tienda/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.nombre

class Producto(models.Model):
    nombre=models.CharField(max_length=50)
    categorias=models.ForeignKey(Categoria, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to='tienda', null=True, blank=True)
    precio=models.FloatField()
    disponible=models.BooleanField(default=True)

    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.nombre

ProyectoWeb/tienda/views.py
from django.shortcuts import render
from .models import Producto

# Create your views here.

def tienda(request):
    productos = Producto.objects.all()
    return render(request, 'tienda/tienda.html', {"productos":productos})

ProyectoWeb/tienda/templates/tienda/tienda.html
{% extends 'proyectoWebApp/base.html' %} {% load static %} {% block content %}

<h1 style="color: azure">TIENDA</h1>

<div class="container">

    <p style="color: white">
      {% if request.user.is_authenticated %}
        <div style="float: right">
          {% include 'carrito/widget.html' %}
        </div>
      {% else %}
        <div class="alert alert-danger text-center">
          Se debe iniciar sesión para realizar un pedido.
        </div>
      {% endif %}
    </p>



  <div class="row">
    {% for producto in productos%}

    <div class="col-md-3">
      <div class="card" style="width: 100%; margin: 5px 5px">
        <img src="{{ producto.imagen.url }}" class="card-img-top" />

        <div class="card-body" style="text-align: center">
          <h7 class="card-title"> {{ producto.nombre }} </h7>
          <p class="card-text">$&nbsp;{{ producto.precio }}</p>
        </div>

        <div class="card-footer text-center">
          <a href="{% url 'carrito:agregar' producto.id %}" class="btn btn-success">Agregar 🛒</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}